name: au_med
description: "AU MedTraker — medication tracker app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  avatar_maker: ^1.7.0
  awesome_snackbar_content: ^0.1.8
  contribution_heatmap: ^0.5.3
  day_night_themed_switcher: ^2.0.2

  drift: ^2.34.0

  fl_chart: ^1.2.0
  flutter:
    sdk: flutter

  flutter_local_notifications: ^22.0.1
  flutter_localizations:
    sdk: flutter
  flutter_longpress_preview: ^0.1.9

  flutter_riverpod: ^3.3.2
  flutter_svg: ^2.0.15
  forui: ^0.23.0

  go_router: ^17.3.0

  intl: ^0.20.2
  json_annotation: ^4.9.0
  orient_ui: ^0.7.0
  icon_plus: ^0.1.1

  shadcn_flutter: ^0.0.52
  shared_preferences: ^2.5.5
  sqlite3_flutter_libs: ^0.6.0+eol
  timezone: ^0.11.0
  uuid: ^4.5.1

  # flutter_launcher_icons: ^0.14.4
  path_provider: ^2.1.6

  babstrap_settings_screen: ^0.1.7
  fluentui_system_icons: ^1.1.273
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.14
  drift_dev: ^2.34.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  riverpod_generator: ^4.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/


flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true